runtime! debian.vim

if has("syntax")
  syntax on
endif

if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif


colo torte
set nu
set ts=4
set sw=4
map <C-A> ggVG"+y
map <F2> :w<CR>
map <F3> :browse e<CR>
map <F4> :browse vsp<CR>
map <F5> :call Run()<CR>
func! Run()
	exec "w"
	exec "!g++ -Wall % -o %<"
	exec "!./%<"
endfunc
